const express = require("express");
const router = express.Router();
const catchAsyncErrors = require("../middleware/catchAsyncErrors");
const ErrorHandler = require("../utils/ErrorHandler");
const Product = require("../model/product");

// POST /api/v2/seed/products — Seed demo products across all categories
router.post(
  "/products",
  catchAsyncErrors(async (req, res, next) => {
    try {
      const demoShop = {
        _id: "seed_shop_001",
        name: "Amazon Marketplace",
        avatar: "default-avatar.png",
        ratings: 4.5,
      };

      const products = [
        // Computers and Laptops
        {
          name: "Apple MacBook Air M2 Chip 13.6-inch Laptop (8GB/256GB SSD)",
          description: "Apple MacBook Air with M2 chip delivers blazing-fast performance with up to 18 hours of battery life. 13.6-inch Liquid Retina display with 500 nits brightness. MagSafe charging, 1080p FaceTime HD camera, and four-speaker sound system. Perfect for work, study, and creative projects.",
          category: "Computers and Laptops",
          tags: "laptop,apple,macbook,m2",
          originalPrice: 119900,
          discountPrice: 99900,
          stock: 25,
          images: ["https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg"],
          ratings: 4.5,
          sold_out: 145,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "HP Pavilion 15 12th Gen Intel Core i5 Laptop (16GB/512GB SSD)",
          description: "HP Pavilion 15 with 12th Gen Intel Core i5-1235U processor. 15.6-inch FHD IPS micro-edge anti-glare display. Intel Iris Xe Graphics, backlit keyboard, fingerprint reader. Windows 11 Home with MS Office 2021. Thin and light design at just 1.75 kg.",
          category: "Computers and Laptops",
          tags: "laptop,hp,intel,windows",
          originalPrice: 72990,
          discountPrice: 58990,
          stock: 40,
          images: ["https://m.media-amazon.com/images/I/61QGMX0Qy+L._SL1500_.jpg"],
          ratings: 4.2,
          sold_out: 230,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "Lenovo IdeaPad Slim 3 AMD Ryzen 5 Laptop (8GB/512GB SSD)",
          description: "Lenovo IdeaPad Slim 3 powered by AMD Ryzen 5 5500U. 15.6-inch FHD display with anti-glare coating. Dolby Audio speakers, HD webcam with privacy shutter. Up to 10 hours battery life. Pre-loaded Windows 11 and MS Office 2021.",
          category: "Computers and Laptops",
          tags: "laptop,lenovo,amd,ryzen",
          originalPrice: 58990,
          discountPrice: 44990,
          stock: 55,
          images: ["https://m.media-amazon.com/images/I/61QGMX0Qy+L._SL1500_.jpg"],
          ratings: 4.1,
          sold_out: 312,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Mobile and Tablets
        {
          name: "Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB RAM, 256GB)",
          description: "Samsung Galaxy S24 Ultra with Galaxy AI. 6.8-inch Dynamic AMOLED 2X display with 2600 nits brightness. Snapdragon 8 Gen 3 processor. 200MP main camera with AI-powered zoom. Built-in S Pen, titanium frame, and 5000mAh battery with 45W fast charging.",
          category: "Mobile and Tablets",
          tags: "mobile,samsung,galaxy,5g",
          originalPrice: 129999,
          discountPrice: 109999,
          stock: 30,
          images: ["https://m.media-amazon.com/images/I/51hqXIFOxnL._SL1500_.jpg"],
          ratings: 4.6,
          sold_out: 89,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "iPhone 15 Pro (256GB) - Natural Titanium",
          description: "iPhone 15 Pro with A17 Pro chip. 6.1-inch Super Retina XDR display with ProMotion. Titanium design, Action Button, and USB-C. 48MP main camera with 5x optical zoom. Always-On display, Dynamic Island, and all-day battery life.",
          category: "Mobile and Tablets",
          tags: "mobile,apple,iphone,5g",
          originalPrice: 134900,
          discountPrice: 126900,
          stock: 20,
          images: ["https://m.media-amazon.com/images/I/61L1ItFgFHL._SL1500_.jpg"],
          ratings: 4.7,
          sold_out: 156,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "OnePlus 12 5G (Flowy Emerald, 12GB RAM, 256GB Storage)",
          description: "OnePlus 12 with Snapdragon 8 Gen 3. 6.82-inch 2K LTPO AMOLED display with 120Hz refresh rate. Hasselblad camera system with 50MP main sensor. 5400mAh battery with 100W SUPERVOOC charging. 0 to 100% in just 26 minutes.",
          category: "Mobile and Tablets",
          tags: "mobile,oneplus,5g,snapdragon",
          originalPrice: 69999,
          discountPrice: 64999,
          stock: 45,
          images: ["https://m.media-amazon.com/images/I/61dMBEx4JjL._SL1500_.jpg"],
          ratings: 4.4,
          sold_out: 201,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Cloths
        {
          name: "Levi's Men's Slim Fit Jeans - Dark Indigo (32W x 32L)",
          description: "Levi's 511 Slim Fit Jeans in dark indigo wash. Made from premium stretch denim for comfort and flexibility. Classic 5-pocket styling with signature Levi's tab. Versatile slim fit that sits below the waist with a narrow leg.",
          category: "Cloths",
          tags: "clothing,jeans,levis,men",
          originalPrice: 3999,
          discountPrice: 1899,
          stock: 100,
          images: ["https://m.media-amazon.com/images/I/61-doQLRjWL._UY741_.jpg"],
          ratings: 4.3,
          sold_out: 567,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "Allen Solly Men's Regular Fit Polo T-Shirt - Navy Blue",
          description: "Allen Solly classic polo t-shirt in navy blue. Made from 100% premium cotton for breathability. Regular fit with ribbed collar and button placket. Ideal for casual outings and office wear. Machine washable.",
          category: "Cloths",
          tags: "clothing,tshirt,men,cotton",
          originalPrice: 1599,
          discountPrice: 799,
          stock: 200,
          images: ["https://m.media-amazon.com/images/I/51JJQM8fYgL._UY741_.jpg"],
          ratings: 4.1,
          sold_out: 890,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "BIBA Women's Cotton Straight Kurta - Maroon Printed",
          description: "BIBA printed straight kurta in maroon. Made from pure cotton with traditional Indian prints. Regular fit with mandarin collar and 3/4 sleeves. Knee-length design perfect for daily wear and festive occasions.",
          category: "Cloths",
          tags: "clothing,women,kurta,cotton",
          originalPrice: 2499,
          discountPrice: 1299,
          stock: 150,
          images: ["https://m.media-amazon.com/images/I/71HMSXP-yFL._UY741_.jpg"],
          ratings: 4.2,
          sold_out: 432,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Shoes
        {
          name: "Nike Air Max 270 Men's Running Shoes - Black/White",
          description: "Nike Air Max 270 with the tallest Air unit yet for all-day comfort. Breathable mesh upper with no-sew overlays. Foam midsole with 270-degree Max Air unit. Rubber outsole with flex grooves for natural motion. Iconic Nike style for running and lifestyle.",
          category: "Shoes",
          tags: "shoes,nike,running,men",
          originalPrice: 12995,
          discountPrice: 8997,
          stock: 60,
          images: ["https://m.media-amazon.com/images/I/61utX8kBDlL._UL1500_.jpg"],
          ratings: 4.4,
          sold_out: 178,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "Puma RS-X Reinvention Unisex Sneakers - White/Blue",
          description: "Puma RS-X Reinvention sneakers with retro-inspired chunky design. Mesh and leather upper with bold color blocking. RS foam cushioning for supreme comfort. Rubber outsole with textured grip. Iconic Puma branding.",
          category: "Shoes",
          tags: "shoes,puma,sneakers,unisex",
          originalPrice: 8999,
          discountPrice: 5399,
          stock: 75,
          images: ["https://m.media-amazon.com/images/I/71Rtm3FRDYL._UL1500_.jpg"],
          ratings: 4.3,
          sold_out: 234,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Accesories
        {
          name: "boAt Rockerz 450 Bluetooth Wireless Headphones - Luscious Black",
          description: "boAt Rockerz 450 wireless headphones with 40mm dynamic drivers. Up to 15 hours playback on a single charge. Padded ear cushions for hours of comfort. Dual connectivity modes (Bluetooth and AUX). Built-in microphone for hands-free calls.",
          category: "Accesories",
          tags: "headphones,boat,wireless,bluetooth",
          originalPrice: 3999,
          discountPrice: 1299,
          stock: 200,
          images: ["https://m.media-amazon.com/images/I/61cx+tASSCL._SL1500_.jpg"],
          ratings: 4.1,
          sold_out: 1245,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "Noise ColorFit Pro 4 Smartwatch - Jet Black",
          description: "Noise ColorFit Pro 4 with 1.72-inch TruView display. Bluetooth calling, 100+ sports modes, and SpO2 monitoring. 24/7 heart rate & sleep tracking. Up to 7 days battery life. IP68 water resistant with 150+ cloud-based watch faces.",
          category: "Accesories",
          tags: "watch,smartwatch,noise,fitness",
          originalPrice: 5999,
          discountPrice: 2999,
          stock: 120,
          images: ["https://m.media-amazon.com/images/I/61I1gCsgq-L._SL1500_.jpg"],
          ratings: 4.0,
          sold_out: 890,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Music and Gaming
        {
          name: "Sony PS5 DualSense Wireless Controller - White",
          description: "PlayStation 5 DualSense wireless controller with haptic feedback and adaptive triggers. Immersive gaming with built-in microphone and speaker. Create button for sharing content. USB-C connectivity with up to 12 hours battery. Compatible with PS5 console.",
          category: "Music and Gaming",
          tags: "gaming,ps5,controller,sony",
          originalPrice: 5990,
          discountPrice: 4990,
          stock: 50,
          images: ["https://m.media-amazon.com/images/I/61tsCJNVqyL._SL1500_.jpg"],
          ratings: 4.7,
          sold_out: 67,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "Logitech G502 HERO High Performance Gaming Mouse",
          description: "Logitech G502 HERO gaming mouse with 25,600 DPI HERO sensor. 11 programmable buttons with on-board memory. Adjustable weight system (5x 3.6g weights). RGB lighting with LIGHTSYNC. Mechanical button tensioning for crisp clicks.",
          category: "Music and Gaming",
          tags: "gaming,mouse,logitech,rgb",
          originalPrice: 6295,
          discountPrice: 3495,
          stock: 80,
          images: ["https://m.media-amazon.com/images/I/61mpMH5TzkL._SL1500_.jpg"],
          ratings: 4.5,
          sold_out: 345,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // cosmetics and body care
        {
          name: "Maybelline New York Fit Me Foundation - Natural Beige 220",
          description: "Maybelline Fit Me Matte + Poreless foundation. Lightweight formula that controls shine and blurs pores. SPF 22 protection for daily wear. Suitable for normal to oily skin. Dermatologist tested and non-comedogenic.",
          category: "cosmetics and body care",
          tags: "cosmetics,foundation,maybelline,makeup",
          originalPrice: 599,
          discountPrice: 399,
          stock: 300,
          images: ["https://m.media-amazon.com/images/I/51UsOJhlJgL._SL1100_.jpg"],
          ratings: 4.2,
          sold_out: 1567,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        {
          name: "The Man Company Charcoal Face Wash for Men (100ml)",
          description: "The Man Company activated charcoal face wash. Deep cleanses pores and removes impurities. Enriched with aloe vera and green tea extracts. SLS-free, paraben-free formula. Controls excess oil while maintaining skin moisture. Suitable for all skin types.",
          category: "cosmetics and body care",
          tags: "skincare,facewash,men,charcoal",
          originalPrice: 499,
          discountPrice: 299,
          stock: 250,
          images: ["https://m.media-amazon.com/images/I/51RHjpdkDrL._SL1500_.jpg"],
          ratings: 4.0,
          sold_out: 789,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Pet Care
        {
          name: "Pedigree Adult Dry Dog Food - Chicken & Vegetables (10kg)",
          description: "Pedigree complete nutrition for adult dogs. Made with real chicken and vegetables. Supports healthy digestion, strong bones, and shiny coat. Enriched with essential vitamins and minerals. Vet recommended and loved by dogs.",
          category: "Pet Care",
          tags: "pet,dog,food,pedigree",
          originalPrice: 1890,
          discountPrice: 1499,
          stock: 100,
          images: ["https://m.media-amazon.com/images/I/71WNMHZ5-SL._SL1500_.jpg"],
          ratings: 4.3,
          sold_out: 456,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
        // Gifts
        {
          name: "Cadbury Celebrations Premium Chocolate Gift Pack (281g)",
          description: "Cadbury Celebrations premium assorted chocolate gift pack. Includes Dairy Milk, 5Star, Gems, Perk, and Bournville. Beautifully designed festive packaging. Perfect for birthdays, anniversaries, Diwali, and all celebrations.",
          category: "Gifts",
          tags: "gifts,chocolate,cadbury,celebration",
          originalPrice: 500,
          discountPrice: 399,
          stock: 500,
          images: ["https://m.media-amazon.com/images/I/81sFNjKCb1L._SL1500_.jpg"],
          ratings: 4.4,
          sold_out: 2345,
          shopId: "seed_shop_001",
          shop: demoShop,
        },
      ];

      // Insert all products
      const created = await Product.insertMany(products);

      res.status(201).json({
        success: true,
        message: `Seeded ${created.length} products across all categories`,
        count: created.length,
      });
    } catch (error) {
      return next(new ErrorHandler(error.message, 500));
    }
  })
);

module.exports = router;
